baseURL = "http://www.example.com"
title = "Miguel Florian"

theme = "hugo-coder"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Miguel Florian"
    description = "John Doe's personal website"
    keywords = "blog,developer,personal"
    info = "Web Developper and UI/UX Designer"
    avatarURL = "images/IMG_20210316_164721.jpg"
    #gravatar = "john.doe@example.com"
    footerContent ="Merci de me suivre"

    dateFormat = "January 2, 2006"

    hideFooter = false
    hideCredits = true
    hideCopyright = false
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

# If you want to use plausible(https://plausible.io) for analytics, add this section
[params.plausibleAnalytics]
    domain = "example.com"
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL = "analytics.example.com"

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
[params.goatCounter]
    code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
[params.cloudflare]
    token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
[params.matomo]
    # Default value is "1", overwrite this if you are cloud-hosting
    siteID = "ABCDE"
    # For cloud-hosting, use provided URL, e.g. example.matomo.cloud
    serverURL = "analytics.example.com"

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
[params.googleTagManager]
    id = "gid"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
	  childsrc = ["'self'"]
	  fontsrc = [
        "'self'",
		    "https://fonts.gstatic.com",
		    "https://cdn.jsdelivr.net/"
    ]
	  formaction = ["'self'"]
	  framesrc = ["'self'"]
	  imgsrc = ["'self'"]
	  objectsrc = ["'none'"]
	  stylesrc = [
        "'self'",
		    "'unsafe-inline'",
		    "https://fonts.googleapis.com/",
		    "https://cdn.jsdelivr.net/"
    ]
	  scriptsrc = [
        "'self'",
		    "'unsafe-inline'",
		    "https://www.google-analytics.com"
    ]
	  prefetchsrc = ["'self'"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/Miguel-Florian/"
[[params.social]]
    name = "Gitlab"
    icon = "fa fa-gitlab"
    weight = 2
    url = "https://gitlab.com/Miguel-Florian/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 3
    url = "https://twitter.com/MiguelFlorian19"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/miguel-florian-b5bb001b"
[[params.social]]
    name = "Instagram"
    icon = "fa fa-instagram"
    weight = 5
    url = "https://www.instagram.com/miguel_florian4/"
[[params.social]]
    name = "Dribble"
    icon = "fa fa-dribbble"
    weight = 6
    url = "https://dribbble.com/Miguel-Noumowe"
    rel = "alternate"
    type = "application/dribbble+xml"


[languages]
    [languages.en]
        languageName = "Francais"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "A propos"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Mes projets"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Me contacter"
            weight = 5
            url = "contact/"


    